version: '3.1'
services:
  postgres:
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data/
  # api:
  #   volumes:
  #     - ../repos/api:/src
  # web:
  #   volumes:
  #     - ../repos/web/build:/usr/share/nginx/html
