version: '3.1'
services:
  pgadmin:
    container_name: skystrata-pgadmin
    image: crunchydata/crunchy-pgadmin4:centos7-10.9-2.4.1
    volumes:
      - /var/lib/pgadmin
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_SETUP_EMAIL=dbuser@whatsmycut.com
      - PGADMIN_SETUP_PASSWORD=123
      - SERVER_PORT=5050
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: skystrata-db
    image: postgres:9.6-alpine
    user: "postgres"
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "11001:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    # restart: always
  # web:
  #   container_name: skystrata-web
  #   build:
  #     context: ../repos/web/
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  # api:
  #   container_name: 'skystrata-api'
  #   build:
  #     context: ../repos/api/
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - SSH_AUTH_SOCK=/ssh-agent
  #   volumes:
  #     - ./:/src
  #     - $SSH_AUTH_SOCK:/ssh-agent
  # prisma:
  #   container_name: wmcp-prisma
  #   image: prismagraphql/prisma:1.34
  #   restart: always
  #   ports:
  #   - "4466:4466"
  #   depends_on:
  #     - postgres
  #   environment:
  #     PRISMA_MANAGEMENT_API_SECRET: 123
  #     PRISMA_CONFIG: |
  #       port: 4466
  #       # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
  #       managementApiSecret: 123
  #       databases:
  #         default:
  #           connector: postgres
  #           host: postgres
  #           port: 5432
  #           database: whatsmycut
  #           schema: whatsmycut$public
  #           user: dbuser
  #           password: 123
  #           migrations: false
  #           rawAccess: true
  #           ssl: false
networks:
  default:
    external:
      name: localnet
